# Generated by Django 5.0.4 on 2024-05-18 14:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pidx',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
