# Generated by Django 5.0.4 on 2024-05-25 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHome', '0002_cartitem_payment_status_cartitem_pidx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10),
        ),
    ]
