# Generated by Django 5.0.4 on 2024-05-25 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0005_alter_booking_opponent_status'),
        ('userHome', '0003_player_user_alter_cartitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsalkit',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminHome.futsal'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='football-bg.jpg', upload_to=''),
        ),
    ]
