# Generated by Django 5.0.4 on 2024-05-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='opponent_status',
            field=models.BooleanField(default=False),
        ),
    ]
