# Generated by Django 5.0.4 on 2024-05-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0003_booking_opponent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='opponent_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10),
        ),
    ]
