# Generated by Django 5.0.1 on 2024-01-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10),
        ),
    ]
