# Generated by Django 5.0.1 on 2024-04-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0006_futsal_addedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
