# Generated by Django 5.0.4 on 2024-05-18 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuth', '0001_initial'),
        ('userHome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userHome.team'),
        ),
    ]
