# Generated by Django 5.0.1 on 2024-02-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_futsal_owner',
            field=models.BooleanField(default=False),
        ),
    ]
